name: Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

env:
  STORYBOOK_STORIES: ${{ vars.STORYBOOK_STORIES }}

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-unstable:
    name: Build unstable
    runs-on: ubuntu-latest
    environment: 'development'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Use nx-set-sha
        uses: nrwl/nx-set-shas@v3
      - name: Install
        run: npm ci
      - name: Package
        run: npm run package
      - name: Store build
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static-unstable
          path: apps/storybook/storybook-static
  build-stable:
    name: Build stable
    if: ${{ github.ref_name == 'main' || github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Use nx-set-sha
        uses: nrwl/nx-set-shas@v3
      - name: Install
        run: npm ci
      - name: Package
        run: npm run package
      - name: Store build
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static-stable
          path: apps/storybook/storybook-static
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          project: ./apps/storybook
          runTests: false
      - name: Chrome components
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          install: false
          project: ./apps/storybook
          command: npm run test:ci
      - name: Firefox Components
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          install: false
          project: ./apps/storybook
          command: npm run test:ci
  deploy-preview:
    name: Preview deploy
    if: ${{ github.ref_name != 'main' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    environment: 'development'
    needs: [build-unstable, test]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v3
        with:
          name: storybook-static-unstable
          path: apps/storybook/storybook-static
      - name: Push to Cloudflare
        uses: cloudflare/pages-action@1
        with:
          branch: ${{ github.head_ref }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: datacom-endeavour
          directory: apps/storybook/storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  deploy-develop:
    name: Deploy develop
    if: ${{ github.event_name == 'push' && github.ref_name == 'develop'}}
    environment: 'development'
    needs: [build-unstable, test]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v3
        with:
          name: storybook-static-unstable
          path: apps/storybook/storybook-static
      - name: Push to Cloudflare
        uses: cloudflare/pages-action@1
        with:
          branch: develop
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: datacom-endeavour
          directory: apps/storybook/storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  deploy-staging:
    name: Deploy staging
    if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
    environment: 'staging'
    needs: [build-stable, test]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v3
        with:
          name: storybook-static-stable
          path: apps/storybook/storybook-static
      - name: Push to Cloudflare
        uses: cloudflare/pages-action@1
        with:
          branch: staging
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: datacom-endeavour
          directory: apps/storybook/storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  deploy-production:
    name: Deploy production
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    environment: 'production'
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build
        uses: actions/download-artifact@v3
        with:
          name: storybook-static
          path: apps/storybook/storybook-static
      - name: Push to Cloudflare
        uses: cloudflare/pages-action@1
        with:
          branch: main
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: datacom-endeavour
          directory: apps/storybook/storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
